apiVersion: v1
kind: Service
metadata:
  name: kube-dns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeDNS"
spec:
  selector:
    k8s-app: kube-dns
  clusterIP:  10.100.88.88
  type: NodePort
  ports:
  - name: dns
    port: 53
    protocol: UDP
    nodePort: 
  - name: dns-tcp
    port: 53
    protocol: TCP
    nodePort: 