apiVersion: v1
kind: Service
metadata:
  name: kube-dns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeDNS"
spec:
  selector:
    k8s-app: kube-dns
  clusterIP: 10.100.88.88
#  clusterIP: 10.0.0.10
  type: NodePort
  ports:
  - name: dns
    port: 53
    nodePort:
    protocol: UDP
  - name: dns-tcp
    port: 53
    nodePort:
    protocol: TCP
