apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    name: redis-slave
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 6379
    nodePort:
  selector:
    name: redis-slave
